version: '3.4'
services:
    goerli-pantheon.dnp.dappnode.eth:
        image: 'goerli-pantheon.dnp.dappnode.eth:0.1.0'
        build: ./build
        volumes:
            - 'goerli:/goerli'
        ports:
            - '127.0.0.1:8546:8546'
            - '127.0.0.1:8545:8545'
            - '55535:30303'
            - '55535:30303/udp'
            - '55534:30304/udp'
volumes:
    goerli: {}
